### PR TITLE
Automatically split up metrics queries based on probe quantity

### PR DESCRIPTION
**Pull request by relud**
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-558)

### CODE REVIEW

**Comment by ncalexan** [comment]
Can we get context on this change?  What's the motivation?

I'm interested because it impacts the generated SQL in ways that surprise me: it expresses the idea at the Python level rather than at the Jinja level, which is where most of the similar logic for grouping, chunking, etc is happening.

**Comment by relud** [comment]
> Can we get context on this change? What's the motivation?

because given enough metrics we can't get it done in a single query

**Review by scholtzan — APPROVED** [review]
Looks great. We might need to do something similar with statistics queries, sometimes if there are a bunch of percentiles computed for different metrics, the queries also reach BigQueries limitations.

**Comment by relud** [comment]
waiting until monday to merge

**Pull request merged**
